<?php

namespace app\common\model;


class Category extends Base
{
    /**
     * 验证字段的方法
     * @param 控制器 $controller
     * @param 验证场景 $scene
     * @param 验证数据 $data
     * @return array|null
     */
    function validateInfo($controller, $scene, $data)
    {
        return parent::validateInfo($controller, $scene, $data); // TODO: Change the autogenerated stub
    }

    /**
     * 获取栏目分类
     * @param int  父级ID
     * @return false|\PDOStatement|string|\think\Collection
     */
    function getCategory($parentId = 0)
    {
        $data = [
            'parent_id' => $parentId,
            //'status' => ['neq', 0]//不等于0，没有被删除的
        ];
        $order = [
            'listorder' => 'desc',
            'id' => 'desc'
        ];
        return $this->where($data)->order($order)->select();
    }

    /**
     *  获取二级栏目分类（没用的方法）
     * @param int $parentId
     * @return false|\PDOStatement|string|\think\Collection
     */
    function getSecondCategory($parentId = 0)
    {
        $data = [
            'parent_id' => ['neq', $parentId],
            'status' => ['neq', 0]//不等于0，没有被删除的
        ];
        $order = [
            'listorder' => 'desc',
            'id' => 'desc'
        ];
        return $this->where($data)->order($order)->select();
    }
    /**
     *  获取二级栏目分类
     * @param int $parentId
     * @return false|\PDOStatement|string|\think\Collection
     */
    function getSecondCategorys($parentId = 0)
    {
        $data = [
            'parent_id' =>$parentId,
//            'status' => ['neq', 0]//不等于0，没有被删除的
        ];
        $order = [
            'listorder' => 'desc',
            'id' => 'desc'
        ];
        return $this->where($data)->order($order)->select();
    }

    /**
     * 根据父级id，获取相应的栏目信息
     * @param int $parentId
     * @return false|\PDOStatement|string|\think\Collection
     */
    function getCategoryById($Id = 0)
    {
        $data = [
            'id' => ['in', $Id],
            'status' => ['neq', 0]//不等于0，没有被删除的
        ];
        $order = [
            'listorder' => 'desc',
            'id' => 'desc'
        ];
        return $this->where($data)->order($order)->select();
    }

    /**
     * 根据父级id，获取主键id值
     * @param int $Id
     * @return false|\PDOStatement|string|\think\Collection
     */
    function getOneCategory($Id = 0)
    {
        $data = [
            'id' =>$Id,
//            'status' => ['neq', 0]//不等于0，没有被删除的
        ];

        return $this->where($data)->find();
//        dump();exit;
    }

    /**
     * 修改商户的状态
     * @param $data 数据
     * @param $controller 模型
     * @return bool|false|int
     */
    function status($data, $controller)
    {
        return parent::status($data, $controller); // TODO: Change the autogenerated stub
    }

}